FROM public.ecr.aws/lambda/python:3.12

# Set working directory to the Lambda task root
WORKDIR ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install boto3==1.34.149 pandas==2.2.2 tenacity==9.0.0 --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY sqs_processor.py .

# Table Maps
COPY tmp/table_maps/ ${LAMBDA_TASK_ROOT}/table_maps/


CMD [ "sqs_processor.lambda_handler" ]