FROM public.ecr.aws/lambda/python:3.12

# Set working directory to the Lambda task root
WORKDIR ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install boto3==1.34.149 pandas==2.2.2 tenacity==9.0.0 --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY step_sync_missing_datasets_lambda.py .

CMD [ "step_sync_missing_datasets_lambda.lambda_handler" ]